Repository video-game-coding-club/geometry-smash, pull requests merged in 2018-11, with the labels that each got.

#238 Add more danger tests
  Dangerfile
  Gemfile
Labels: enhancement

#242 Refactor some code
  main.js
Labels: bug, enhancement

#243 Refactor code for the two signs
  main.js
Labels: bug

#244 Fix incorrect variable name
  main.js
Labels: bug

#246 Cleanup
  README.md
Labels: documentation

#247 Publish webpage from Travis-CI
  .travis.yml
Labels: documentation

#245 Add babel support
  .babelrc
  package.json
Labels: enhancement

#248 I changed the message
  main.js
Labels: bug

#249 I DID SOMETHING AWSEOME!!!!!!!!!!!!!!!!
  main.js
Labels: enhancement

#250 Comma functain
  main.js
Labels: enhancement

#251 i added greater key
  main.js
Labels: enhancement

#253 Don't deploy gh-pages for now
  .travis.yml
Labels: documentation
