Repository video-game-coding-club/geometry-smash, pull requests merged in 2018-10, with the labels that each got.

#120 Jump mod1
  main.js
Labels: enhancement, hacktoberfest

#128 Make the level longer
  main.js
Labels: enhancement

#135 Game Over
  main.js
Labels: enhancement, hacktoberfest

#136 Fix incorrect property reference
  main.js
Labels: bug

#141 Added fork and cloning as steps for external contributors
  DeveloperWorkflow.md
Labels: documentation

#139 Create favicon and add to game.html
  _layouts/default.html
  favicon.ico
  game.html
Labels: enhancement

#137 Change the mouse event
  main.js
Labels: enhancement

#143 Fix relative link to favicon
  _layouts/default.html
Labels: bug

#142 Incremental update towards collision
  main.js
Labels: bug, hacktoberfest

#144 Collision improvements
  main.js
Labels: enhancement, hacktoberfest

#152 Fix obsolete assignment
  main.js
Labels: bug

#157 drawed bounding box !!!!!!!!!!!!!!!$$$$
  main.js
Labels: enhancement

#158 Bounding box fixes
  main.js
Labels: bug, hacktoberfest

#159 Fix the position of the hero bounding box
  main.js
Labels: enhancement

#160 Bounding box for saw
  main.js
Labels: bug, hacktoberfest

#167 Workflow
  CodeAnywhere.md
  DeveloperWorkflow.md
  Git.md
  README.md
  TestLocally.md
  _config.yml
Labels: documentation

#169 Add syntax highlighting for shell commands
  CodeAnywhere.md
  DeveloperWorkflow.md
  Git.md
  TestLocally.md
Labels: documentation

#170 Add some style to hashtag
  README.md
Labels: documentation

#173 Fix GitPod link
  _layouts/default.html
Labels: bug

#172 Fix spelling
  CodeAnywhere.md
Labels: documentation

#174 Rename variables and fix game over
  main.js
Labels: bug, hacktoberfest

#168 Small fixes
  main.js
Labels: enhancement, hacktoberfest

#177 Fix some collision stuff
  main.js
Labels: bug, hacktoberfest

#178 Fix bounding box for laser.
  main.js
Labels: enhancement, hacktoberfest
