Repository video-game-coding-club/geometry-smash, pull requests merged in 2018-12, with the labels that each got.

#254 Publish
  .travis.yml
  Gemfile
  _config.yml
  lint.sh
  package-lock.json
  package.json
Labels: documentation

#258 Travis
  .travis.yml
Labels: enhancement

#259 Fix incorrect `baseurl`
  _config.yml
Labels: bug, documentation

#260 Rename build stage
  .travis.yml
Labels: documentation, enhancement

#263 moved obs_speed
  main.js
Labels: enhancement

#265 Adis 9675847690
  main.js
Labels: enhancement

#252 Added new attributes
  main.js
Labels: enhancement

#266 Obstacle logic
  main.js
Labels: enhancement

#267 Update GitPod section with new usage plan
  README.md
Labels: documentation

#268 Fix links
  _config.yml
  _layouts/default.html
Labels: documentation

#269 Update npm package versions
  package-lock.json
  package.json
Labels: CI

#276 i added authors to our page
  README.md
Labels: documentation

#272 i moved step debug
  main.js
Labels: bug

#277 Keep original main.js file for debugging
  .travis.yml
Labels: enhancement

#273 i made gravity
  main.js
Labels: enhancement
