Repository video-game-coding-club/geometry-smash, pull requests merged in 2019-01, with the labels that each got.

#280 i placed gravity on the top of the screen
  main.js
Labels: enhancement

#281 yay
  main.js
Labels: enhancement

#282 Gravity
  main.js
Labels: enhancement

#279 hi i did something wierd
  main.js
Labels: enhancement

#278 Background
  assets/snowflake.jpg
  main.js
Labels: enhancement

#298 Add "Hello World" example for CircleCI
  .circleci/config.yml
Labels: CI

#300 Add CircleCI badge to webpage
  README.md
Labels: CI

#297 Make Danger a little bit less dangerous
  Dangerfile
Labels: enhancement

#301 Improve visual formatting of badges
  README.md
Labels: documentation

#290 Added image via upload
  assets/dodecahedron.jpg
Labels: enhancement

#292 Add files via upload
  assets/Dragon.jpg
  main.js
Labels: enhancement

#294 Add files via upload
  assets/bone_dragon.jpg
  main.js
Labels: enhancement

#293 Add files via upload
  assets/griffin.jpg
  main.js
Labels: enhancement

#303 Fix spelling
  main.js
Labels: bug
